import Card, { CardHeader } from "../components/ui/Card";
import Badge from "../components/ui/Badge";
import Metric from "../components/ui/Metric";
import Button from "../components/ui/Button";
import Icon from "../components/ui/Icon";
import { AI_FINDINGS } from "../data/case001";
import type { IconName } from "../types";

export default function FindingsPage() {
  return (
    <div className="content">
      <div className="findings-summary">
        <div>
          <span>ANALYSIS STATUS</span>
          <strong>18 evidence items analyzed</strong>
          <small>Last updated 8 minutes ago</small>
        </div>
        <div style={{ display: "flex", gap: 16 }}>
          <Metric value="03" label="OPEN" detail="Needs review" tone="amber-text" />
          <Metric value="07" label="VERIFIED" detail="Accepted findings" tone="green-text" />
          <Metric value="02" label="DISMISSED" detail="By investigator" />
        </div>
      </div>

      <div className="findings-layout">
        <div className="findings-list">
          {AI_FINDINGS.map((finding, index) => (
            <Card className="finding-card" key={finding.id}>
              <div className="finding-card-top">
                <div className={`finding-icon ${finding.tone}`}>
                  <Icon
                    name={
                      finding.type === "CORRELATION"
                        ? "link"
                        : finding.type === "TIMELINE"
                        ? "clock"
                        : "alert"
                    }
                  />
                </div>
                <div>
                  <div>
                    <Badge tone={finding.tone}>{finding.type}</Badge>
                    <span>FINDING {String(index + 1).padStart(2, "0")}</span>
                  </div>
                  <strong>{finding.title}</strong>
                </div>
                <div className="confidence-score">
                  <strong>{finding.confidence}%</strong>
                  <span>CONFIDENCE</span>
                </div>
              </div>
              <p>{finding.body}</p>
              <div className="source-list">
                {finding.sources.map((source) => (
                  <button key={source}>
                    <Icon name="link" />
                    {source}
                  </button>
                ))}
              </div>
              <div className="finding-actions">
                <span>
                  <Icon name="spark" /> Generated by NEXUS · Model NeMo-Retriever
                </span>
                <div>
                  <Button variant="ghost">Dismiss</Button>
                  <Button icon="check" variant="primary">
                    Verify finding
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <Card className="review-panel">
          <CardHeader title="Review queue" eyebrow="INVESTIGATOR ACTION" />
          <div className="review-progress">
            <div>
              <strong>7 of 10</strong>
              <span>findings reviewed</span>
            </div>
            <b>
              <i style={{ width: "70%" }} />
            </b>
            <small>70% complete</small>
          </div>
          <div className="review-stats">
            <span>
              <i className="green-dot" />Verified <b>7</b>
            </span>
            <span>
              <i className="amber-dot" />Open <b>3</b>
            </span>
            <span>
              <i className="gray-dot" />Dismissed <b>2</b>
            </span>
          </div>
          <div className="review-note">
            <Icon name="alert" />
            <span>
              <strong>Review required</strong>
              <br />
              AI findings must be verified by an investigator before report inclusion.
            </span>
          </div>
        </Card>
      </div>
    </div>
  );
}
